import { useEffect, useState } from 'react';
import { api } from '../api';
import { Button, PageHeader, SurfaceCard, BottomSheet, EmptyState, ProgressBar } from './ui';

// H：Goal 可完全沒有 Plan，Plan 也可以不掛 Goal；這裡只管理聚合與指派。
export default function GoalsView({ plans = [], reloadPlans }) {
  const [goals, setGoals] = useState([]); const [selected, setSelected] = useState(null); const [sheet, setSheet] = useState(null); const [form, setForm] = useState({ name: '', description: '', target_date: '' }); const [error, setError] = useState('');
  const load = () => api('/goals').then(setGoals).catch(e => setError(e.message)); useEffect(() => { load(); }, []);
  const save = async () => { try { setError(''); if (selected) await api(`/goals/${selected.id}`, { method: 'PATCH', body: form }); else await api('/goals', { method: 'POST', body: form }); setSheet(null); setSelected(null); load(); } catch (e) { setError(e.message); } };
  const edit = g => { setSelected(g || null); setForm(g ? { name: g.name, description: g.description || '', target_date: g.target_date || '' } : { name: '', description: '', target_date: '' }); setSheet('edit'); };
  const assign = async (plan, goalId) => { try { await api(`/plans/${plan.id}`, { method: 'PATCH', body: { goal_id: goalId || null } }); await reloadPlans?.(); load(); } catch (e) { setError(e.message); } };
  return <div className="main"><PageHeader title="目標" subtitle="用目標串起多個讀書計畫" actions={<Button size="sm" variant="primary" onClick={() => edit(null)}>新增目標</Button>} /><div className="main-body">{error && <SurfaceCard tone="warning">{error}</SurfaceCard>}
    {goals.length === 0 ? <EmptyState title="還沒有目標" description="例如：第二次段考、學測複習。目標可先建立，之後再加入計畫。" action={<Button variant="primary" onClick={() => edit(null)}>建立第一個目標</Button>} /> : goals.map(g => <SurfaceCard key={g.id} large style={{ marginBottom: 12 }}><div className="row"><div><b>{g.name}</b><div className="ui-meta">{g.target_date ? `目標日 ${g.target_date}` : '未設定目標日'}</div></div><Button size="sm" variant="tertiary" style={{ marginLeft: 'auto' }} onClick={() => edit(g)}>編輯</Button></div>{g.description && <div className="ui-meta" style={{ marginTop: 8 }}>{g.description}</div>}<div style={{ marginTop: 12 }}><ProgressBar value={g.progress.completed_tasks} max={g.progress.total_tasks} label={`${g.name} ${g.progress.percent}%`} /><div className="ui-meta" style={{ marginTop: 4 }}>{g.progress.percent}%・{g.plans.length} 個計畫</div></div>{g.plans.map(p => <div className="ui-row" key={p.id}><div className="ui-row-main"><div className="ui-row-title">{p.name}</div><div className="ui-row-sub">{p.completed_task_count || 0} / {p.task_count || 0} 項完成</div></div><Button size="sm" variant="tertiary" onClick={() => assign(p, null)}>移出</Button></div>)}</SurfaceCard>)}
    <section className="ui-section"><div className="ui-section-title">尚未歸屬目標的計畫</div>{plans.filter(p => !p.goal_id && !p.isLegacy).map(p => <SurfaceCard key={p.id} style={{ marginBottom: 8 }}><div className="row"><span style={{ flex: 1 }}>{p.name}</span><select aria-label={`將${p.name}指派到目標`} defaultValue="" onChange={e => e.target.value && assign(p, Number(e.target.value))}><option value="">加入目標…</option>{goals.map(g => <option key={g.id} value={g.id}>{g.name}</option>)}</select></div></SurfaceCard>)}</section>
  </div>{sheet === 'edit' && <BottomSheet onClose={() => setSheet(null)} label="編輯目標"><b>{selected ? '編輯目標' : '新增目標'}</b><input autoFocus placeholder="目標名稱" value={form.name} onChange={e => setForm(x => ({ ...x, name: e.target.value }))} /><textarea placeholder="說明（選填）" rows="3" value={form.description} onChange={e => setForm(x => ({ ...x, description: e.target.value }))} /><label className="ui-meta">目標日期</label><input type="date" value={form.target_date} onChange={e => setForm(x => ({ ...x, target_date: e.target.value }))} /><div className="row" style={{ marginTop: 16 }}><Button onClick={() => setSheet(null)}>取消</Button><Button variant="primary" style={{ marginLeft: 'auto' }} disabled={!form.name.trim()} onClick={save}>儲存</Button></div></BottomSheet>}</div>;
}
